name: "Create Pull Request"
on: 
  schedule:
    - cron: "0 0 1 1 *"
jobs:
  rebase:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Modify File
        run: |
          cd /../../actions-test
          sed '$ a Again' abc.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
  
