#####################################################################################
# Github Action to check references to closed issues in code.
#
# Workflow starts when:
# 1) push on master branch
# 2) pull request is opened or synchronized or reopened
#
#####################################################################################
name: "Check no closed issue references"

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  check_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Download actions-test
        uses: actions/checkout@v2
        with:
          repository: Vyom-Yadav/actions-test
          ref: master
          path: actions-test

      - name: Check Issues
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: |
          cd actions-test
          ./.ci/no_old_refs.sh
