#####################################################################################
# Github Action to check references to closed issues in code.
#
# Workflow starts when:
# 1) push on master branch
# 2) pull request is opened or synchronized or reopened
#
#####################################################################################
name: "Check no closed issue references"

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  check_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Download actions-test
        uses: actions/checkout@v2
      - name: PR linked issues
        id: links
        uses: mondeja/pr-linked-issues-action@v2
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Issues
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          LINKED_ISSUES: '${{ steps.links.outputs.issues }}'
        run: |
          ./.ci/no_old_refs.sh
      - name: Print bunch of stuff
        run: |
          echo Github action reposiroty: $GITHUB_ACTION_REPOSITORY
          echo Github base ref: $GITHUB_BASE_REF
          ehco Github head ref: $GITHUB_HEAD_REF
          echo Github repository: $GITHUB_REPOSITORY
          echo Github workspace: $GITHUB_WORKSPACE
